language: csharp
solution: OmniKassa.sln

sudo: required

branches:
  only:
    - master

matrix:
  include:
    - dotnet: 1.0.4
      mono: none
      dist: trusty

script:
  - dotnet restore
  - dotnet test tests/OmniKassa.Tests/OmniKassa.Tests.csproj -c Release -f netcoreapp1.1